#!/usr/bin/env python3
"""Generate PARITY.md from the medit source tree.

The point of generating it is that the denominator is objective: you cannot
rewrite what you cannot enumerate, and a hand-kept checklist quietly loses the
rows nobody remembers.  Behavioural features (the 1.8.x list) cannot be
scraped from an action id, so they are declared here and merged in.

Usage: tools/gen-parity.py /path/to/medit > PARITY.md
"""
import os
import re
import sys

# Behavioural features with no action id to scrape.  Verified by the scripted
# GUI self-test and a manual pass, not by the presence of a menu entry.
BEHAVIOURAL = [
    ("Vertical / box selection", "Ctrl+drag, copy, paste at caret column, paste into box", 2),
    ("Fast long-line loading", "truncate past 4096 chars with click-to-reveal", 2),
    ("Split view", "up to 4 views of one document per tab", 1),
    ("Split notebook", "two independent tab groups per window", 3),
    ("Ctrl+0 / Ctrl+9", "shift selected lines by exactly one space", 2),
    ("Code folding: braces", "C/C++/Java/JS and friends", 2),
    ("Code folding: end-keyword", "Matlab/Octave/Pascal", 2),
    ("Code folding: indentation", "Python/YAML", 2),
    ("Toggle matching bracket", "Ctrl+]", 2),
    ("Ctrl+scroll font zoom", "temporary, 4-72 pt, not persisted", 2),
    ("Breadcrumb folder navigation", "clickable path segments in the file browser", 5),
    ("Split terminal panels", "recursive horizontal/vertical splits", 7),
    ("Terminal colour schemes", "the 10 named ANSI palettes", 7),
    ("Customizable colour themes", "the 8 style schemes", 1),
    ("Encoding detection with prompt", "try-list, BOM, mixed line endings", 1),
    ("Session save and restore", "windows, tabs, carets, layout", 3),
    ("Single instance with file hand-off", "second invocation reuses the running one", 3),
]

DROPPED = [
    ("Detachable floating panes", "docking on four edges is kept"),
    ("Wiki markup preview", "Markdown preview is kept"),
    ("XSMP desktop session management", "X11 only; session.json covers continuity"),
    ("OS clipboard file transfer", "LCL cannot initiate an OS file drag portably"),
    ("Dragging files out of the app", "Windows-only in LCL; not worth the split"),
    ("freedesktop trash spec", "confirm-and-delete instead"),
    ("Runtime ui.xml customization", "superseded by the shortcut editor"),
    ("Embedded CPython", "external python3 for tools instead"),
]

UI_FILES = [
    "moo/mooedit/medit.xml",
    "moo/mooedit/mooedit.xml",
    "moo/moofileview/moofileview.xml",
]


def actions(root):
    found = set()
    for rel in UI_FILES:
        path = os.path.join(root, rel)
        if not os.path.exists(path):
            continue
        with open(path, encoding="utf-8", errors="replace") as fh:
            found.update(re.findall(r'action="([A-Za-z0-9_]+)"', fh.read()))
    return sorted(found)


def prefs_keys(root):
    path = os.path.join(root, "moo/mooedit/mooeditprefs.h")
    if not os.path.exists(path):
        return []
    with open(path, encoding="utf-8", errors="replace") as fh:
        text = fh.read()
    return sorted(set(re.findall(r'MOO_EDIT_PREFS_[A-Z0-9_]+\s+"([^"]+)"', text)))


def user_tools(root):
    names = []
    for rel in ("moo/plugins/usertools/menu.xml",
                "moo/plugins/usertools/context.xml"):
        path = os.path.join(root, rel)
        if not os.path.exists(path):
            continue
        with open(path, encoding="utf-8", errors="replace") as fh:
            names += re.findall(r"<name>([^<]+)</name>", fh.read())
    return names


def table(rows):
    out = ["| Feature | medit | led | Decision |", "|---|---|---|---|"]
    out += rows
    return out


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    root = sys.argv[1]

    lines = [
        "# led parity checklist",
        "",
        "Generated by `tools/gen-parity.py` from the medit tree, then maintained",
        "by hand.  `Decision` is one of **done**, **replaced** (with what),",
        "**dropped**, or **phase-N**.",
        "",
        "## Behavioural features",
        "",
        "The 1.8.x additions that give medit its character.  None of these can be",
        "checked off by the presence of a menu entry.",
        "",
    ]
    lines += table([
        "| %s<br><sub>%s</sub> | yes | | phase-%d |" % (name, note, phase)
        for name, note, phase in BEHAVIOURAL
    ])

    acts = actions(root)
    lines += ["", "## Actions (%d)" % len(acts), ""]
    lines += table(["| `%s` | yes | | |" % a for a in acts])

    keys = prefs_keys(root)
    if keys:
        lines += ["", "## Preference keys (%d)" % len(keys), ""]
        lines += table(["| `%s` | yes | | |" % k for k in keys])

    tools = user_tools(root)
    if tools:
        lines += ["", "## Shipped user tools (%d)" % len(tools), ""]
        lines += table(["| %s | yes | | phase-4 |" % t for t in tools])

    lines += ["", "## Dropped, agreed up front", "",
              "| Feature | Why |", "|---|---|"]
    lines += ["| %s | %s |" % (name, why) for name, why in DROPPED]
    lines.append("")

    print("\n".join(lines))


if __name__ == "__main__":
    main()
